version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
  

jobs:
  build:
    docker:
      - image: cimg/ruby:2.6.8
    working_directory: ~/Im_here
    steps:
      - checkout:
          path: ~/Im_here
      - ruby/install-deps
      # - restore_cache:
      #     name: bundle installの結果をrestore
      #     keys: 
      #       - v1-dependencies-{{ checksum "Gemfile.lock" }}
      #       - v1-dependencies-


  test:
    docker:
      - image: cimg/ruby:2.6.8
      # - image: circleci/mysql:5.7
        environment:
          RAILS_ENV: test
      - image: circleci/mysql:5.7
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
          MYSQL_ROOT_PASSWORD: ''
          MYSQL_DATABASE: ci_rails_sample_test
    working_directory: ~/Im_here
    steps:
      - checkout:
          path: ~/Im_here
      - ruby/install-deps
      # - run:
      #     name: Database setup
      #     command: bundle exec rails db:migrate
      # - run:
      #     name: test
      #     command: bundle exec rake test

  # deploy:
  #   docker:
  #     - image: cimg/ruby:2.7.5
  #   steps:
  #     - setup_remote_docker:
  #         version: 19.03.13
  #     - heroku/install
  #     - run:
  #         name: heroku login
  #         command: heroku container:login
  #     - run:
  #         name: push docker image
  #         command: heroku container:push web -a $HEROKU_APP_NAME
  #     - run:
  #         name: release docker image
  #         command: heroku container:release web -a $HEROKU_APP_NAME
  #     - run:
  #         name: database setup
  #         command: heroku run bundle exec rake db:migrate RAILS_ENV=production -a $HEROKU_APP_NAME

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build
      # - deploy:
      #     requires:
      #       - test
      #     filters:
      #       branches:
      #         only: main